export default {
    icon1: require('../assets/images/icon1.png'),
    icon2: require('../assets/images/icon2.png'),
    icon3: require('../assets/images/icon3.png'),
    icon4: require('../assets/images/icon4.png'),
    icon5: require('../assets/images/icon5.png'),
    icon6: require('../assets/images/icon6.png'),
    icon7: require('../assets/images/icon7.png'),
    nft1:require('../assets/images/nft1.png'),
    nft2:require('../assets/images/nft2.png'),
    nft3:require('../assets/images/nft3.png'),
    nft4:require('../assets/images/nft4.png'),
    nft5:require('../assets/images/nft5.png'),
    nft6:require('../assets/images/nft6.png'),
    nft7:require('../assets/images/nft7.png'),
    nft8:require('../assets/images/nft8.png'),
    nft9:require('../assets/images/nft9.png'),
    nft10:require('../assets/images/nft10.png'),
    nft11:require('../assets/images/nft11.png'),
    nft12:require('../assets/images/nft12.png'),
    nft13:require('../assets/images/nft13.png'),
    nft14:require('../assets/images/nft14.png'),
    nft15:require('../assets/images/nft15.png'),
    nft16:require('../assets/images/nft16.png'),
    nft17:require('../assets/images/nft17.png'),
    nft18:require('../assets/images/nft18.png'),

};